/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.slackers.inc.Lists;

import java.util.LinkedList;

/**
 *
 * @author jestrada
 */
public class CTList {
    private final LinkedList ctList = new LinkedList();
    
    private static class Helper {
        private static final CTList instance = new CTList();
    }
    
    public CTList(){
        ctList.add(new CT("0", "ADMINISTRATIVE WITHDRAWAL"));
        ctList.add(new CT("00", "ADMINISTRATIVE WITHDRAWAL"));
        ctList.add(new CT("000", "ADMINISTRATIVE WITHDRAWAL"));
        ctList.add(new CT("100", "STRAIGHT WHISKY"));
        ctList.add(new CT("101", "STRAIGHT BOURBON WHISKY"));
        ctList.add(new CT("102", "STRAIGHT RYE WHISKY"));
        ctList.add(new CT("103", "STRAIGHT CORN WHISKY"));
        ctList.add(new CT("104", "RUM LEMON FLAVORED"));
        ctList.add(new CT("105", "RUM CHERRY FLAVORED"));
        ctList.add(new CT("106", "RUM CHOCOLATE FLAVORED"));
        ctList.add(new CT("107", "RUM MINT FLAVORED"));
        ctList.add(new CT("108", "RUM PEPPERMINT FLAVORED"));
        ctList.add(new CT("109", "OTHER STRAIGHT WHISKY"));
        ctList.add(new CT("110", "WHISKY BOTTLED IN BOND (BIB)"));
        ctList.add(new CT("111", "BOURBON WHISKY BIB"));
        ctList.add(new CT("112", "RYE WHISKY BIB"));
        ctList.add(new CT("113", "CORN WHISKY BIB"));
        ctList.add(new CT("119", "OTHER WHISKY BIB"));
        ctList.add(new CT("120", "STRAIGHT WHISKY BLENDS"));
        ctList.add(new CT("121", "STRAIGHT BOURBON WHISKY BLENDS"));
        ctList.add(new CT("122", "STRAIGHT RYE WHISKY BLENDS"));
        ctList.add(new CT("123", "STRAIGHT CORN WHISKY BLENDS"));
        ctList.add(new CT("129", "OTHER STRAIGHT BLENDED WHISKY"));
        ctList.add(new CT("130", "WHISKY BLENDS"));
        ctList.add(new CT("131", "BLENDED BOURBON WHISKY"));
        ctList.add(new CT("132", "BLENDED RYE WHISKY"));
        ctList.add(new CT("133", "BLENDED CORN WHISKY"));
        ctList.add(new CT("134", "BLENDED LIGHT WHISKY"));
        ctList.add(new CT("137", "BLENDED WHISKY"));
        ctList.add(new CT("138", "DILUTED BLENDED WHISKY"));
        ctList.add(new CT("139", "OTHER WHISKY BLENDS"));
        ctList.add(new CT("140", "WHISKY"));
        ctList.add(new CT("141", "BOURBON WHISKY"));
        ctList.add(new CT("142", "RYE WHISKY"));
        ctList.add(new CT("143", "CORN WHISKY"));
        ctList.add(new CT("144", "LIGHT WHISKY"));
        ctList.add(new CT("146", "WHISKY PROPRIETARY"));
        ctList.add(new CT("147", "SPIRIT WHISKY"));
        ctList.add(new CT("148", "DILUTED WHISKY"));
        ctList.add(new CT("149", "OTHER WHISKY (FLAVORED)"));
        ctList.add(new CT("150", "SCOTCH WHISKY"));
        ctList.add(new CT("151", "SCOTCH WHISKY FB"));
        ctList.add(new CT("152", "SCOTCH WHISKY USB"));
        ctList.add(new CT("153", "SINGLE MALT SCOTCH WHISKY"));
        ctList.add(new CT("154", "UNBLENDED SCOTCH WHISKY USB"));
        ctList.add(new CT("157", "DILUTED SCOTCH WHISKY FB"));
        ctList.add(new CT("158", "DILUTED SCOTCH WHISKY USB"));
        ctList.add(new CT("160", "CANADIAN WHISKY"));
        ctList.add(new CT("161", "CANADIAN WHISKY FB"));
        ctList.add(new CT("162", "CANADIAN WHISKY USB"));
        ctList.add(new CT("167", "DILUTED CANADIAN WHISKY FB"));
        ctList.add(new CT("168", "DILUTED CANADIAN WHISKY USB"));
        ctList.add(new CT("170", "IRISH WHISKY"));
        ctList.add(new CT("171", "IRISH WHISKY FB"));
        ctList.add(new CT("172", "IRISH WHISKY USB"));
        ctList.add(new CT("177", "DILUTED IRISH WHISKY FB"));
        ctList.add(new CT("178", "DILUTED IRISH WHISKY USB"));
        ctList.add(new CT("181", "WHISKY ORANGE FLAVORED"));
        ctList.add(new CT("182", "WHISKY GRAPE FLAVORED"));
        ctList.add(new CT("183", "WHISKY LIME FLAVORED"));
        ctList.add(new CT("184", "WHISKY LEMON FLAVORED"));
        ctList.add(new CT("185", "WHISKY CHERRY FLAVORED"));
        ctList.add(new CT("186", "WHISKY CHOCOLATE FLAVORED"));
        ctList.add(new CT("187", "WHISKY MINT FLAVORED"));
        ctList.add(new CT("188", "WHISKY PEPPERMINT FLAVORED"));
        ctList.add(new CT("189", "WHISKY PTHER FLAVORED"));
        ctList.add(new CT("190", "OTHER IMPORTED WHISKY"));
        ctList.add(new CT("191", "OTHER IMPORTED WHISKY FB"));
        ctList.add(new CT("192", "OTHER IMPORTED WHISKY USB"));
        ctList.add(new CT("197", "DILUTED OTHER IMPORTED WHISKY FB"));
        ctList.add(new CT("198", "DILUTED OTHER IMPORTED WHISKY USB"));
        ctList.add(new CT("200", "DISTILLED GIN"));
        ctList.add(new CT("201", "LONDON DRY DISTILLED GIN"));
        ctList.add(new CT("209", "OTHER DISTILLED GIN"));
        ctList.add(new CT("210", "GIN"));
        ctList.add(new CT("211", "LONDON DRY GIN"));
        ctList.add(new CT("219", "OTHER GIN"));
        ctList.add(new CT("230", "GIN - FLAVORED"));
        ctList.add(new CT("231", "GIN - MINT FLAVORED"));
        ctList.add(new CT("232", "GIN - ORANGE FLAVORED"));
        ctList.add(new CT("233", "GIN - LEMON FLAVORED"));
        ctList.add(new CT("239", "OTHER GIN - FLAVORED"));
        ctList.add(new CT("248", "DILUTED GIN"));
        ctList.add(new CT("250", "DISTILLED GIN"));
        ctList.add(new CT("251", "LONDON DRY DISTILLED GIN FB"));
        ctList.add(new CT("252", "LONDON DRY DISTILLED GIN USB"));
        ctList.add(new CT("258", "OTHER DISTILLED GIN FB"));
        ctList.add(new CT("259", "OTHER DISTILLED GIN USB"));
        ctList.add(new CT("260", "GIN"));
        ctList.add(new CT("261", "LONDON DRY GIN FB"));
        ctList.add(new CT("262", "LONDON DRY GIN USB"));
        ctList.add(new CT("268", "OTHER GIN FB"));
        ctList.add(new CT("269", "OTHER GIN USB"));
        ctList.add(new CT("280", "GIN - FLAVORED"));
        ctList.add(new CT("281", "GIN - MINT FLAVORED"));
        ctList.add(new CT("282", "GIN - ORANGE FLAVORED"));
        ctList.add(new CT("283", "GIN - LEMON FLAVORED"));
        ctList.add(new CT("284", "GIN - CHERRY FLAVORED"));
        ctList.add(new CT("285", "GIN - APPLE FLAVORED"));
        ctList.add(new CT("286", "GIN - BLACKBERRY FLAVORED"));
        ctList.add(new CT("287", "GIN - PEACH FLAVORED"));
        ctList.add(new CT("288", "GIN - GRAPE FLAVORED"));
        ctList.add(new CT("289", "OTHER GIN - FLAVORED"));
        ctList.add(new CT("290", "OTHER GIN"));
        ctList.add(new CT("297", "DILUTED GIN FB"));
        ctList.add(new CT("298", "DILUTED GIN USB"));
        ctList.add(new CT("300", "VODKA"));
        ctList.add(new CT("301", "VODKA 80-90 PROOF"));
        ctList.add(new CT("310", "VODKA"));
        ctList.add(new CT("311", "VODKA 90-99 PROOF"));
        ctList.add(new CT("320", "VODKA"));
        ctList.add(new CT("321", "VODKA 100 PROOF UP"));
        ctList.add(new CT("330", "VODKA - FLAVORED"));
        ctList.add(new CT("331", "VODKA - ORANGE FLAVORED"));
        ctList.add(new CT("332", "VODKA - GRAPE FLAVORED"));
        ctList.add(new CT("333", "VODKA - LIME FLAVORED"));
        ctList.add(new CT("334", "VODKA - LEMON FLAVORED"));
        ctList.add(new CT("335", "VODKA - CHERRY FLAVORED"));
        ctList.add(new CT("336", "VODKA - CHOCOLATE FLAVORED"));
        ctList.add(new CT("337", "VODKA - MINT FLAVORED"));
        ctList.add(new CT("338", "VODKA - PEPPERMINT FLAVORED"));
        ctList.add(new CT("339", "VODKA - OTHER FLAVORED"));
        ctList.add(new CT("340", "OTHER VODKA"));
        ctList.add(new CT("348", "DILUTED VODKA"));
        ctList.add(new CT("350", "VODKA"));
        ctList.add(new CT("351", "VODKA 80-90 PROOF FB"));
        ctList.add(new CT("352", "VODKA 80-90 PROOF USB"));
        ctList.add(new CT("360", "VODKA"));
        ctList.add(new CT("361", "VODKA 90-99 PROOF FB"));
        ctList.add(new CT("362", "VODKA 90-99 PROOF USB"));
        ctList.add(new CT("370", "VODKA"));
        ctList.add(new CT("371", "VODKA 100 PROOF UP FB"));
        ctList.add(new CT("372", "VODKA 100 PROOF UP USB"));
        ctList.add(new CT("380", "VODKA - FLAVORED"));
        ctList.add(new CT("381", "VODKA - ORANGE FLAVORED"));
        ctList.add(new CT("382", "VODKA - GRAPE FLAVORED"));
        ctList.add(new CT("383", "VODKA - LIME FLAVORED"));
        ctList.add(new CT("384", "VODKA - LEMON FLAVORED"));
        ctList.add(new CT("385", "VODKA - CHERRY FLAVORED"));
        ctList.add(new CT("386", "VODKA - CHOCOLATE FLAVORED"));
        ctList.add(new CT("387", "VODKA - MINT FLAVORED"));
        ctList.add(new CT("388", "VODKA - PEPPERMINT FLAVORED"));
        ctList.add(new CT("389", "VODKA - OTHER FLAVORED"));
        ctList.add(new CT("390", "OTHER VODKA"));
        ctList.add(new CT("397", "DILUTED VODKA FB"));
        ctList.add(new CT("398", "DILUTED VODKA USB"));
        ctList.add(new CT("400", "UR.S. RUM (WHITE)"));
        ctList.add(new CT("401", "PUERTO RICAN RUM (WHITE)"));
        ctList.add(new CT("402", "VIRGIN ISLANDS RUM (WHITE)"));
        ctList.add(new CT("403", "HAWAIIAN RUM (WHITE)"));
        ctList.add(new CT("404", "FLORIDA RUM (WHITE)"));
        ctList.add(new CT("409", "OTHER RUM (WHITE)"));
        ctList.add(new CT("410", "U.S. RUM (GOLD)"));
        ctList.add(new CT("411", "PUERTO RICAN RUM (GOLD)"));
        ctList.add(new CT("412", "VIRGIN ISLAND RUM (GOLD)"));
        ctList.add(new CT("413", "HAWAIIAN RUM (GOLD)"));
        ctList.add(new CT("414", "FLORIDA RUM (GOLD)"));
        ctList.add(new CT("419", "OTHER RUM (GOLD)"));
        ctList.add(new CT("430", "RUM FLAVORED (BOLD)"));
        ctList.add(new CT("431", "RUM ORANGE GLAVORED"));
        ctList.add(new CT("432", "RUM GRAPE FLAVORED"));
        ctList.add(new CT("433", "RUM LIME FLAVORED"));
        ctList.add(new CT("434", "RUM LEMON FLAVORED"));
        ctList.add(new CT("435", "RUM CHERRY FLAVORED"));
        ctList.add(new CT("436", "RUM CHOCOLATE FLAVORED"));
        ctList.add(new CT("437", "RUM MINT FLAVORED"));
        ctList.add(new CT("438", "RUM PEPPERMINT FLAVORED"));
        ctList.add(new CT("439", "RUM OTHER FLAVORED"));
        ctList.add(new CT("440", "OTHER WHITE RUM"));
        ctList.add(new CT("441", "FLAVORED RUM (BOLD)"));
        ctList.add(new CT("442", "RUM ORANGE FLAVORED"));
        ctList.add(new CT("443", "RUM GRAPE FLAVORED"));
        ctList.add(new CT("444", "RUM LIME FLAVORED"));
        ctList.add(new CT("445", "RUM OTHER FLAVORED"));
        ctList.add(new CT("447", "DILUTED RUM (WHITE)"));
        ctList.add(new CT("448", "DILUTED RUM (GOLD)"));
        ctList.add(new CT("449", "DOMESTIC FLAVORED RUM"));
        ctList.add(new CT("450", "FOREIGN RUM"));
        ctList.add(new CT("451", "CUBAN RUM WHITE FB"));
        ctList.add(new CT("452", "CUBAN RUM WHITE USB"));
        ctList.add(new CT("453", "CUBAN RUM GOLD FB"));
        ctList.add(new CT("454", "CUBAN RUM GOLD USB"));
        ctList.add(new CT("459", "OTHER FORIEGN RUM"));
        ctList.add(new CT("461", "JAMAICAN RUM WHITE FB"));
        ctList.add(new CT("462", "JAMAICAN RUM WHITE USB"));
        ctList.add(new CT("463", "JAMAICAN RUM GOLD FB"));
        ctList.add(new CT("464", "JAMICAN RUM GOLD USB"));
        ctList.add(new CT("471", "GUIANAN RUM WHITE FB"));
        ctList.add(new CT("472", "GUIANAN RUM WHITE USB"));
        ctList.add(new CT("473", "DUTCH GUIANAN RUM GOLD FB"));
        ctList.add(new CT("474", "DUTCH GUIANAN RUM GOLD USB"));
        ctList.add(new CT("475", "FRENCH GUIANAN RUM FB"));
        ctList.add(new CT("476", "FRENCH GUIANAN RUM USB"));
        ctList.add(new CT("481", "MARTINICAN RUM WHITE FB"));
        ctList.add(new CT("482", "MARTINICAN RUM WHITE USB"));
        ctList.add(new CT("483", "MARTINICAN RUM GOLD FB"));
        ctList.add(new CT("484", "MARTINICAN RUM GOLD USB"));
        ctList.add(new CT("490", "OTHER FOREIGN RUM"));
        ctList.add(new CT("491", "OTHER RUM WHITE FB"));
        ctList.add(new CT("492", "OTHER RUM WHITE USB"));
        ctList.add(new CT("493", "OTHER RUM GOLD FB"));
        ctList.add(new CT("494", "OTHER RUM GOLD USB"));
        ctList.add(new CT("495", "DILUTED RUM WHITE FB"));
        ctList.add(new CT("496", "DILUTED RUM WHITE USB"));
        ctList.add(new CT("497", "DILUTED RUM GOLD FB"));
        ctList.add(new CT("498", "DILUTED RUM GOLD USB"));
        ctList.add(new CT("499", "IMPORTED FLAVORED RUM"));
        ctList.add(new CT("500", "CALIFORNIA GRAPE BRANDY"));
        ctList.add(new CT("501", "CALIFORNIA BRANDY"));
        ctList.add(new CT("502", "CALIFORNIA DRIED BRANDY"));
        ctList.add(new CT("503", "CALIFORNIA LEES BRANDY"));
        ctList.add(new CT("504", "CALIFORNIA POMACE OR MARC BRANDY"));
        ctList.add(new CT("505", "CALIFORNIA RESIDUE BRANDY"));
        ctList.add(new CT("506", "CALIFORNIA NEUTRAL BRANDY"));
        ctList.add(new CT("509", "OTHER CALIFORNIA BRANDY"));
        ctList.add(new CT("510", "NEW YORK GRAPE BRANDY"));
        ctList.add(new CT("511", "NEW YORK BRANDY"));
        ctList.add(new CT("512", "NEW YORK DRIED BRANDY"));
        ctList.add(new CT("513", "NEW YORK LEES BRANDY"));
        ctList.add(new CT("514", "NEW YORK POMACE OR MARC BRANDY"));
        ctList.add(new CT("515", "NEW YORK RESIDUE BRANDY"));
        ctList.add(new CT("516", "NEW YORK NEUTRAL BRANDY"));
        ctList.add(new CT("519", "OTHER NEW YORK BRANDY"));
        ctList.add(new CT("520", "OTHER DOMESTIC GRAPE BRANDY"));
        ctList.add(new CT("521", "BRANDY"));
        ctList.add(new CT("522", "DRIED BRANDY"));
        ctList.add(new CT("523", "LEES BRANDY"));
        ctList.add(new CT("524", "POMACE OR MARC BRANDY"));
        ctList.add(new CT("525", "RESIDUE BRANDY"));
        ctList.add(new CT("526", "NEUTRAL BRANDY"));
        ctList.add(new CT("527", "IMMATURE BRANDY"));
        ctList.add(new CT("529", "OTHER BRANDY"));
        ctList.add(new CT("530", "BRANDY - FLAVORED"));
        ctList.add(new CT("531", "BRANDY - APRICOT FLAVORED"));
        ctList.add(new CT("532", "BRANDY - BLACKBERRY FLAVORED"));
        ctList.add(new CT("533", "BRANDY - PEACH FLAVORED"));
        ctList.add(new CT("534", "BRANDY - CHERRY FLAVORED"));
        ctList.add(new CT("535", "BRANDY - GINGER FLAVORED"));
        ctList.add(new CT("536", "BRANDY - COFFEE FLAVORED"));
        ctList.add(new CT("537", "BRANDY APPLE FLAVORED"));
        ctList.add(new CT("538", "BFRANDY PEAR FLAVORED"));
        ctList.add(new CT("539", "OTHER BRANDY - FLAVORED"));
        ctList.add(new CT("540", "FRUIT BRANDY"));
        ctList.add(new CT("541", "APPLE BRANDY"));
        ctList.add(new CT("542", "CHERRY BRANDY"));
        ctList.add(new CT("543", "PLUM BRANDY"));
        ctList.add(new CT("544", "BLACKBERRY BRANDY"));
        ctList.add(new CT("545", "BLENDED APPLE JACK BRANDY"));
        ctList.add(new CT("546", "PEAR BRANDY"));
        ctList.add(new CT("547", "APRICOT BRANDY"));
        ctList.add(new CT("548", "DILUTED BRANDY"));
        ctList.add(new CT("549", "OTHER FRUIT BRANDY"));
        ctList.add(new CT("550", "FRENCH BRANDY"));
        ctList.add(new CT("551", "COGNAC (BRANDY) FB"));
        ctList.add(new CT("552", "COGNAC (BRANDY) USB"));
        ctList.add(new CT("553", "ARMAGNAC (BRANDY) FB"));
        ctList.add(new CT("554", "ARMAGNAC (BRANDY) USB"));
        ctList.add(new CT("558", "OTHER FRENCH BRANDY FB"));
        ctList.add(new CT("559", "OTHER FRENCH BRANDY USB"));
        ctList.add(new CT("560", "OTHER FOREIGN BRANDY"));
        ctList.add(new CT("561", "ITALIAN GRAPE BRANDY FB"));
        ctList.add(new CT("562", "ITALIAN GRAPE BRANDY USB"));
        ctList.add(new CT("563", "SPANISH GRAPE BRANDY FB"));
        ctList.add(new CT("564", "SPANISH GRAPE BRANDY USB"));
        ctList.add(new CT("565", "PORTUGUESE GRAPE BRANDY FB"));
        ctList.add(new CT("566", "PORTUGUESE GRAPE BRANDY USB"));
        ctList.add(new CT("567", "GREEK GRAPE BRANDY FB"));
        ctList.add(new CT("568", "GREEK GRAPE BRANDY USB"));
        ctList.add(new CT("571", "GERMAN GRAPE BRANDY FB"));
        ctList.add(new CT("572", "GERMAN GRAPE BRANDY USB"));
        ctList.add(new CT("573", "AUSTRALIAN GRAPE BRANDY FB"));
        ctList.add(new CT("574", "AUSTRALIAN GRAPE BRANDY USB"));
        ctList.add(new CT("575", "SOUTH AFRICAN GRAPE BRANDY FB"));
        ctList.add(new CT("576", "SOUTH AFRICAN GRAPE BRANDY USB"));
        ctList.add(new CT("580", "OTHER FOREIGN BRANDY (CONT.)"));
        ctList.add(new CT("581", "BRANDY APRICOT FLAVORED"));
        ctList.add(new CT("582", "BRANDY BLACKBERRY FLAVORED"));
        ctList.add(new CT("583", "BRANDY PEACH FLAVORED"));
        ctList.add(new CT("584", "BRANDY CHERRY FLAVORED"));
        ctList.add(new CT("585", "BRANDY GINGER FLAVORED"));
        ctList.add(new CT("586", "BRANDY COFFEE FLAVORED"));
        ctList.add(new CT("587", "BRANDY APPLE FLAVORED"));
        ctList.add(new CT("588", "OTHER GRAPE BRANDY (PISCO, GRAPPA) FB"));
        ctList.add(new CT("589", "OTHER GRAPE BRANDY (GRAPPA) USB"));
        ctList.add(new CT("590", "FOREIGN FRUIT BRANDY"));
        ctList.add(new CT("591", "APPLE BRANDY (CALVADOS)"));
        ctList.add(new CT("592", "CHERRY BRANDY"));
        ctList.add(new CT("593", "PLUM BRANDY (SLIVOVITZ)"));
        ctList.add(new CT("594", "BLACKBERRY BRANDY"));
        ctList.add(new CT("595", "BLENDED APPLE JACK BRANDY"));
        ctList.add(new CT("596", "APRICOT BRANDY"));
        ctList.add(new CT("597", "DILUTED BRANDY FB"));
        ctList.add(new CT("598", "DILUTED BRANDY USB"));
        ctList.add(new CT("599", "OTHER FRUIT BRANDY"));
        ctList.add(new CT("600", "CORDIALS (FRUIT & PEELS)"));
        ctList.add(new CT("601", "FRUIT FLAVORED LIQUEURS"));
        ctList.add(new CT("603", "CURACAO"));
        ctList.add(new CT("604", "TRIPLE SEC"));
        ctList.add(new CT("605", "SLOE GIN"));
        ctList.add(new CT("606", "ROCK & RYE, RUM & BRANDY (ETC.)"));
        ctList.add(new CT("607", "FRUITS & PEELS SCHNAPPS LIQUEUR"));
        ctList.add(new CT("609", "OTHER FRUITS & PEELS LIQUEURS"));
        ctList.add(new CT("610", "CORDIALS (HERBS & SEEDS)"));
        ctList.add(new CT("611", "ANISETTE, OUZO, OJEN"));
        ctList.add(new CT("612", "COFFEE (CAFE) LIQUEUR"));
        ctList.add(new CT("613", "KUMMEL"));
        ctList.add(new CT("614", "PEPPERMINT SCHNAPPS"));
        ctList.add(new CT("615", "HERBS AND SEEDS SCHNAPPS LIQUEUR"));
        ctList.add(new CT("616", "AMARETTO"));
        ctList.add(new CT("617", "SAMBUCA"));
        ctList.add(new CT("618", "ARACK/RAKI/ARAK"));
        ctList.add(new CT("619", "OTHER (HERBS & SEEDS)"));
        ctList.add(new CT("620", "CORDIALS (CREMES OR CREAMS)"));
        ctList.add(new CT("621", "CREME DE CACAO WHITE"));
        ctList.add(new CT("622", "CREME DE CACAO BROWN"));
        ctList.add(new CT("623", "CREME DE MENTHE WHITE"));
        ctList.add(new CT("624", "CREME DE MENTHE GREEN"));
        ctList.add(new CT("625", "CREME DE ALMOND (NOYAUX)"));
        ctList.add(new CT("627", "DAIRY CREAM LIQUEUR/CORDIAL"));
        ctList.add(new CT("628", "NON DAIRY CREME LIQUEUR/CORDIAL"));
        ctList.add(new CT("629", "OTHER LIQUEUR (CREME OR CREAMS)"));
        ctList.add(new CT("632", "BLACKBERRY FLAVORED BRANDY"));
        ctList.add(new CT("638", "LIQUEUR & BRANDY"));
        ctList.add(new CT("640", "SPECIALTIES & PROPRIETARIES"));
        ctList.add(new CT("641", "WHISKY SPECIALTIES"));
        ctList.add(new CT("642", "GIN SPECIALTIES"));
        ctList.add(new CT("643", "VODKA SPECIALTIES"));
        ctList.add(new CT("644", "RUM SPECIALTIES"));
        ctList.add(new CT("645", "LIQUEURS (WHISKY)"));
        ctList.add(new CT("646", "LIQUEURS (GIN)"));
        ctList.add(new CT("647", "LIQUEURS (VODKA)"));
        ctList.add(new CT("648", "LIQUEURS (RUM)"));
        ctList.add(new CT("649", "OTHER SPECIALTIES & PROPRIETARIES"));
        ctList.add(new CT("650", "CORDIALS (FRUIT & PEELS)"));
        ctList.add(new CT("651", "FRUIT FLAVORED LIQUEURS"));
        ctList.add(new CT("653", "CURACAO"));
        ctList.add(new CT("654", "TRIPLE SEC"));
        ctList.add(new CT("655", "SLOE GIN"));
        ctList.add(new CT("656", "ROCK & RYE, RUM & BRANDY (ETC)"));
        ctList.add(new CT("657", "FRUITS & PEELS SCHNAPPS LIQUEUR"));
        ctList.add(new CT("659", "OTHER FRUIT & PEELS LIQUEURS"));
        ctList.add(new CT("660", "CORDIALS (HERBS & SEEDS)"));
        ctList.add(new CT("661", "ANISETTE, OUZO, OJEN"));
        ctList.add(new CT("662", "COFFEE (CAFE) LIQUEUR"));
        ctList.add(new CT("663", "KUMMEL"));
        ctList.add(new CT("664", "PEPPERMINT SCHNAPPS"));
        ctList.add(new CT("665", "HERBS & SEEDS SCHNAPPS LIQUEUR"));
        ctList.add(new CT("666", "AMARETTO"));
        ctList.add(new CT("667", "SAMBUCA"));
        ctList.add(new CT("668", "ARACK/RAKI/ARAK"));
        ctList.add(new CT("669", "OTHER HERB & SEED CORDIALS/LIQUEURS"));
        ctList.add(new CT("670", "CORDIALS (CREMES OR CREAMS)"));
        ctList.add(new CT("671", "CREME DE CACAO WHITE"));
        ctList.add(new CT("672", "CREME DE CACAO BROWN"));
        ctList.add(new CT("673", "CREME DE MENTHE WHITE"));
        ctList.add(new CT("674", "CREME DE MENTHE GREEN"));
        ctList.add(new CT("675", "CREME DE ALMOND (NOYAUX)"));
        ctList.add(new CT("677", "DAIRY CREAM LIQUEUR/CORDIAL"));
        ctList.add(new CT("678", "NON DAIRY CREME LIQUEUR/CORDIAL"));
        ctList.add(new CT("679", "OTHER LIQUEUR (CREMES OR CREAMS)"));
        ctList.add(new CT("680", "FLAVORED BRANDY"));
        ctList.add(new CT("681", "APRICOT FLAVORED BRANDY"));
        ctList.add(new CT("682", "BLACKBERRY FLAVORED BRANDY"));
        ctList.add(new CT("683", "PEACH FLAVORED BRANDY"));
        ctList.add(new CT("684", "CHERRY FLAVORED BRANDY"));
        ctList.add(new CT("685", "GINGER FLAVORED BRANDY"));
        ctList.add(new CT("688", "LIQUEUR & BRANDY"));
        ctList.add(new CT("689", "OTHER FLAVORED BRANDY"));
        ctList.add(new CT("690", "SPECIALITIES & PROPRIETARIES"));
        ctList.add(new CT("691", "WHISKY SPECIALTIES"));
        ctList.add(new CT("692", "GIN SPECIALTIES"));
        ctList.add(new CT("693", "VODKA SPECIALTIES"));
        ctList.add(new CT("694", "RUM SPECIALTIES"));
        ctList.add(new CT("695", "LIQUEURS (WHISKY)"));
        ctList.add(new CT("696", "LIQUEURS (GIN)"));
        ctList.add(new CT("697", "LIQUEURS (VODKA)"));
        ctList.add(new CT("698", "LIQUEURS (RUM)"));
        ctList.add(new CT("699", "OTHER SPECIALTIES & PROPRIETARIES"));
        ctList.add(new CT("700", "COCKTAILS 48 PROOF UP"));
        ctList.add(new CT("701", "WHISKY MANHATTAN (48 PROOF UP)"));
        ctList.add(new CT("702", "WHISKY OLD FASHIONED (48 PROOF UP)"));
        ctList.add(new CT("703", "WHISKY SOUR (48 PROOF UP )"));
        ctList.add(new CT("704", "MARGARITA (48 PROOF UP)"));
        ctList.add(new CT("706", "GIN MARTINI (48 PROOF UP)"));
        ctList.add(new CT("707", "GIN SOUR (48 PROOF UP)"));
        ctList.add(new CT("710", "COCKTAILS 48 PROOF UP (CONT)"));
        ctList.add(new CT("711", "VODKA MARTINI (48 PROOF UP)"));
        ctList.add(new CT("714", "DAIQUIRI (48 PROOF UP)"));
        ctList.add(new CT("716", "BRANDY STINGER (48 PROOF UP)"));
        ctList.add(new CT("717", "BRANDY SIDE CAR (48 PROOF UP)"));
        ctList.add(new CT("718", "COLADA (48PROOF UP)"));
        ctList.add(new CT("719", "OTHER COCTAILS (48PROOF UP)"));
        ctList.add(new CT("720", "COCKTAILS UNDER 48 PROOF"));
        ctList.add(new CT("721", "WHISKY MANHATTAN (UNDER 48 PROOF)"));
        ctList.add(new CT("722", "WHISKY OLD FASHIONED (UNDER 48 PROOF)"));
        ctList.add(new CT("723", "WHISKY SOUR (UNDER 48 PROOF)"));
        ctList.add(new CT("724", "MARGARITA (UNDER 48 PROOF)"));
        ctList.add(new CT("725", "OTHER TEQUILA-BASED COCKTAILS (UNDER 48 PROOF)"));
        ctList.add(new CT("726", "GIN MARTINI (UNDER 48 PROOF)"));
        ctList.add(new CT("727", "GIN SOUR (UNDER 48 PROOF)"));
        ctList.add(new CT("730", "COCKTAILS UNDER 48 PROOF (CONT)"));
        ctList.add(new CT("731", "VODKA MARTINI (UNDER 48 PROOF)"));
        ctList.add(new CT("734", "DAIQUIRI (UNDER 48 PROOF)"));
        ctList.add(new CT("736", "BRANDY STINGER (UNDER 48 PROOF)"));
        ctList.add(new CT("737", "BRANDY SIDE CAR (UNDER 48 PROOF)"));
        ctList.add(new CT("738", "COLADA (UNDER 48 PROOF)"));
        ctList.add(new CT("739", "OTHER COCKTAILS (UNDER 48 PROOF)"));
        ctList.add(new CT("740", "MIXED DRINKS-HI BALLS COCKTAILS"));
        ctList.add(new CT("741", "SCREW DRIVER"));
        ctList.add(new CT("742", "COLLINS"));
        ctList.add(new CT("743", "BLOODY MARY"));
        ctList.add(new CT("747", "EGG NOG"));
        ctList.add(new CT("749", "OTHER MIXED DRINKS HI-BALLS COCKTAILS"));
        ctList.add(new CT("750", "COCKTAILS 48 PROOF UP"));
        ctList.add(new CT("751", "WHISKY MANHATTAN (48 PROOF UP)"));
        ctList.add(new CT("752", "WHISKY OLD FASHIONED (48 PROOF UP)"));
        ctList.add(new CT("753", "WHISKY SOUR  (48 PROOF UP)"));
        ctList.add(new CT("754", "MARGARITA 48 PROOF UP"));
        ctList.add(new CT("756", "GIN MARTINI 48 PROOF UP"));
        ctList.add(new CT("757", "GIN SOUR 48 PROOF UP"));
        ctList.add(new CT("761", "VODKA MARTINI 48 PROOF UP"));
        ctList.add(new CT("764", "DAIQUIRI 48 PROOF UP"));
        ctList.add(new CT("766", "BRANDY STINGER  48 PROOF UP"));
        ctList.add(new CT("767", "BRANDY SIDE CAR 48 PROOF UP"));
        ctList.add(new CT("768", "COLADA (48 PROOF UP )"));
        ctList.add(new CT("769", "OTHER COCKTAILS (48 PROOF UP)"));
        ctList.add(new CT("770", "COCKTAILS UNDER 48 PROOF"));
        ctList.add(new CT("771", "WHISKY MANHATTAN UNDER 48 PROOF"));
        ctList.add(new CT("772", "WHISKY OLD FASHIONED UNDER 48 PROOF"));
        ctList.add(new CT("773", "WHISKY SOUR UNDER 48 PROOF"));
        ctList.add(new CT("774", "MARGARITA UNDER 48 PROOF"));
        ctList.add(new CT("775", "OTHER TEQUILA-BASED COCKTAILS (UNDER 48 PROOF)"));
        ctList.add(new CT("776", "GIN MARTINI UNDER 48 PROOF"));
        ctList.add(new CT("777", "GIN SOUR UNDER 48 PROOF"));
        ctList.add(new CT("780", "COCKTAILS UNDER 48 PR(CONT)"));
        ctList.add(new CT("781", "VODKA MARTINI  UNDER 48 PROOF"));
        ctList.add(new CT("782", "VODKA SOUR UNDER 48 PROOF"));
        ctList.add(new CT("784", "DAIQUIRI UNDER 48 PROOF"));
        ctList.add(new CT("786", "BRANDY STINGER UNDER 48 PROOF"));
        ctList.add(new CT("787", "BRANDY SIDE CAR UNDER 48 PROOF"));
        ctList.add(new CT("788", "COLADA (UNDER 48 PROOF )"));
        ctList.add(new CT("789", "OTHER COCKTAILS (UNDER 48 PROOF)"));
        ctList.add(new CT("790", "MIXED DRINKS-HI BALLS COCKTAILS"));
        ctList.add(new CT("791", "SCREW DRIVER"));
        ctList.add(new CT("792", "COLLINS"));
        ctList.add(new CT("793", "BLOODY MARY"));
        ctList.add(new CT("797", "EGG NOG"));
        ctList.add(new CT("799", "OTHER MIXED DRINKS HI-BALLS COCKTAILS"));
        ctList.add(new CT("80", "TABLE RED WINE"));
        ctList.add(new CT("80A", "ROSE WINE"));
        ctList.add(new CT("81", "TABLE WHITE WINE"));
        ctList.add(new CT("82", "TABLE FLAVORED WINE"));
        ctList.add(new CT("83", "TABLE FRUIT WINE"));
        ctList.add(new CT("84", "SPARKLING WINE/CHAMPAGNE"));
        ctList.add(new CT("85", "CARBONATED WINE"));
        ctList.add(new CT("86", "VERMOUTH/MIXED TYPES"));
        ctList.add(new CT("87", "DESSERT FLAVORED WINE"));
        ctList.add(new CT("88", "DESSERT /PORT/SHERRY/(COOKING) WINE"));
        ctList.add(new CT("89", "DESSERT FRUIT WINE"));
        ctList.add(new CT("900", "MALT BEVERAGES"));
        ctList.add(new CT("901", "BEER"));
        ctList.add(new CT("902", "ALE"));
        ctList.add(new CT("903", "MALT LIQUOR"));
        ctList.add(new CT("904", "STOUT"));
        ctList.add(new CT("905", "PORTER"));
        ctList.add(new CT("906", "MALT BEVERAGES SPECIALITIES - FLAVORED"));
        ctList.add(new CT("907", "CEREAL BEVERAGES - NEAR BEER (NON ALCOHOLIC)"));
        ctList.add(new CT("909", "OTHER MALT BEVERAGES (BEER)"));
        ctList.add(new CT("920", "OTHER SPIRITS"));
        ctList.add(new CT("921", "NEUTRAL SPIRITS - GRAIN"));
        ctList.add(new CT("922", "NEUTRAL SPIRITS - FRUIT"));
        ctList.add(new CT("923", "NEUTRAL SPIRITS - CANE"));
        ctList.add(new CT("924", "NEUTRAL SPIRITS - VEGETABLE"));
        ctList.add(new CT("925", "NEUTRAL SPIRITS - PETROLEUM"));
        ctList.add(new CT("926", "BITTERS - BEVERAGE"));
        ctList.add(new CT("928", "GRAIN SPIRITS"));
        ctList.add(new CT("929", "OTHER SPIRITS"));
        ctList.add(new CT("931", "SAKE"));
        ctList.add(new CT("934", "SAKE - DOMESTIC FLAVORED"));
        ctList.add(new CT("940", "NON ALCOHOLIC MIXES"));
        ctList.add(new CT("950", "MALT BEVERAGES"));
        ctList.add(new CT("951", "BEER"));
        ctList.add(new CT("952", "ALE"));
        ctList.add(new CT("953", "MALT LIQUOR"));
        ctList.add(new CT("954", "STOUT"));
        ctList.add(new CT("955", "PORTER"));
        ctList.add(new CT("956", "MALT BEVERAGES SPECIALITIES"));
        ctList.add(new CT("957", "CEREAL BEVERAGES - NEAR BEER (NON ALCOHOLIC)"));
        ctList.add(new CT("959", "OTHER MALT BEVERAGES"));
        ctList.add(new CT("970", "OTHER SPIRITS"));
        ctList.add(new CT("971", "NEUTRAL SPIRITS - GRAIN"));
        ctList.add(new CT("972", "NEUTRAL SPIRITS - FRUIT"));
        ctList.add(new CT("973", "NEUTRAL SPIRITS - CANE"));
        ctList.add(new CT("974", "NEUTRAL SPIRITS - VEGETABLE"));
        ctList.add(new CT("975", "NEUTRAL SPIRITS - PETROLEUM"));
        ctList.add(new CT("976", "BITTERS - BEVERAGE*"));
        ctList.add(new CT("977", "TEQUILA FB"));
        ctList.add(new CT("978", "TEQUILA USB"));
        ctList.add(new CT("979", "MEZCAL"));
        ctList.add(new CT("980", "MEZCAL FB"));
        ctList.add(new CT("981", "SAKE - IMPORTED"));
        ctList.add(new CT("982", "MEZCAL US"));
        ctList.add(new CT("984", "SAKE - IMPORTED FLAVORED"));
        ctList.add(new CT("985", "DILUTED TEQUILA FB"));
        ctList.add(new CT("986", "DILUTED TEQUILA USB"));
        ctList.add(new CT("990", "NON ALCOHOL MIXES"));
    }
    
    public CTList getCTList(){
        return Helper.instance;
    }
    
}
