/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.slackers.inc.Lists;

import java.util.LinkedList;

/**
 *
 * @author jestrada
 */
public class OriginList {
    public LinkedList originList = new LinkedList();
    public OriginList(){
        originList.add(new Origin("00", "AMERICAN"));
        originList.add(new Origin("01", "CALIFORNIA"));
        originList.add(new Origin("02", "NEW YORK"));
        originList.add(new Origin("03", "NEW JERSEY"));
        originList.add(new Origin("04", "ILLINOIS"));
        originList.add(new Origin("05", "VIRGINIA"));
        originList.add(new Origin("06", "MICHIGAN"));
        originList.add(new Origin("07", "WASHINGTON"));
        originList.add(new Origin("08", "GEORGIA"));
        originList.add(new Origin("09", "OHIO"));
        originList.add(new Origin("10", "ALABAMA"));
        originList.add(new Origin("11", "ARIZONA"));
        originList.add(new Origin("12", "ARKANSAS"));
        originList.add(new Origin("13", "COLORADO"));
        originList.add(new Origin("14", "CONNECTICUT"));
        originList.add(new Origin("15", "DELAWARE"));
        originList.add(new Origin("16", "FLORIDA"));
        originList.add(new Origin("17", "HAWAII"));
        originList.add(new Origin("18", "IDAHO"));
        originList.add(new Origin("19", "INDIANA"));
        originList.add(new Origin("20", "IOWA"));
        originList.add(new Origin("21", "KANSAS"));
        originList.add(new Origin("22", "KENTUCKY"));
        originList.add(new Origin("23", "LOUISIANA"));
        originList.add(new Origin("24", "MAINE"));
        originList.add(new Origin("25", "MARYLAND"));
        originList.add(new Origin("26", "MASSACHUSETTS"));
        originList.add(new Origin("27", "MINNESOTA"));
        originList.add(new Origin("28", "MISSISSIPPI"));
        originList.add(new Origin("29", "MISSOURI"));
        originList.add(new Origin("30", "MONTANA"));
        originList.add(new Origin("31", "NEBRASKA"));
        originList.add(new Origin("32", "NEVADA"));
        originList.add(new Origin("33", "NEW HAMPSHIRE"));
        originList.add(new Origin("34", "NEW MEXICO"));
        originList.add(new Origin("35", "NORTH CAROLINA"));
        originList.add(new Origin("36", "NORTH DAKOTA"));
        originList.add(new Origin("37", "OKLAHOMA"));
        originList.add(new Origin("38", "OREGON"));
        originList.add(new Origin("39", "PENNSYLVANIA"));
        originList.add(new Origin("3A", "MONACO"));
        originList.add(new Origin("40", "RHODE ISLAND"));
        originList.add(new Origin("41", "SOUTH CAROLINA"));
        originList.add(new Origin("42", "SOUTH DAKOTA"));
        originList.add(new Origin("43", "TENNESSEE"));
        originList.add(new Origin("44", "TEXAS"));
        originList.add(new Origin("45", "UTAH"));
        originList.add(new Origin("46", "VERMONT"));
        originList.add(new Origin("47", "WEST VIRGINIA"));
        originList.add(new Origin("48", "WISCONSIN"));
        originList.add(new Origin("49", "WYOMING"));
        originList.add(new Origin("4A", "PUERTO RICO"));
        originList.add(new Origin("4B", "VIRGIN ISLANDS, US"));
        originList.add(new Origin("4C", "BERMUDA"));
        originList.add(new Origin("4D", "DOMINICAN REPUBLIC"));
        originList.add(new Origin("4E", "ALASKA"));
        originList.add(new Origin("4F", "NICARAGUA"));
        originList.add(new Origin("4G", "BAHAMAS"));
        originList.add(new Origin("4H", "BARBADOS"));
        originList.add(new Origin("4I", "CURACAO"));
        originList.add(new Origin("4J", "KENYA"));
        originList.add(new Origin("4K", "DISTRICT OF COLUMBIA"));
        originList.add(new Origin("4L", "KOSOVO"));
        originList.add(new Origin("4M", "ERITREA"));
        originList.add(new Origin("4N", "CAMBODIA"));
        originList.add(new Origin("4P", "ARUBA"));
        originList.add(new Origin("4R", "TANZANIA"));
        originList.add(new Origin("4S", "UGANDA"));
        originList.add(new Origin("4U", "GREAT BRITAIN"));
        originList.add(new Origin("4V", "TAHITI"));
        originList.add(new Origin("4W", "FIJI"));
        originList.add(new Origin("4X", "CABO VERDE, REPUBLIC OF"));
        originList.add(new Origin("4Y", "ANTIGUA AND BARBUDA"));
        originList.add(new Origin("4Z", "TIBET"));
        originList.add(new Origin("50", "ITALY"));
        originList.add(new Origin("51", "FRANCE"));
        originList.add(new Origin("52", "SPAIN"));
        originList.add(new Origin("53", "GERMANY"));
        originList.add(new Origin("54", "PORTUGAL"));
        originList.add(new Origin("55", "DENMARK"));
        originList.add(new Origin("56", "ISRAEL"));
        originList.add(new Origin("57", "GREECE"));
        originList.add(new Origin("58", "YUGOSLAVIA"));
        originList.add(new Origin("59", "JAPAN"));
        originList.add(new Origin("5A", "EL SALVADOR"));
        originList.add(new Origin("5B", "SWEDEN"));
        originList.add(new Origin("5C", "NORWAY"));
        originList.add(new Origin("5D", "SOUTH KOREA"));
        originList.add(new Origin("5E", "IRELAND"));
        originList.add(new Origin("5F", "LEBANON"));
        originList.add(new Origin("5G", "THAILAND"));
        originList.add(new Origin("5H", "ICELAND"));
        originList.add(new Origin("5I", "INDIA"));
        originList.add(new Origin("5J", "JAMAICA"));
        originList.add(new Origin("5K", "SCOTLAND"));
        originList.add(new Origin("5L", "HONDURAS"));
        originList.add(new Origin("5M", "GUATEMALA"));
        originList.add(new Origin("5N", "HAITI"));
        originList.add(new Origin("5O", "SLOVAK REPUBLIC"));
        originList.add(new Origin("5P", "GUYANA"));
        originList.add(new Origin("5Q", "ETHIOPIA"));
        originList.add(new Origin("5R", "SINGAPORE"));
        originList.add(new Origin("5S", "PHILIPPINES"));
        originList.add(new Origin("5T", "GRENADA"));
        originList.add(new Origin("5U", "ZIMBABWE"));
        originList.add(new Origin("5V", "NIGERIA"));
        originList.add(new Origin("5W", "IVORY COAST"));
        originList.add(new Origin("5Y", "CZECH REPUBLIC"));
        originList.add(new Origin("5Z", "VIETNAM"));
        originList.add(new Origin("60", "ALBANIA"));
        originList.add(new Origin("61", "ALGERIA"));
        originList.add(new Origin("62", "ARGENTINA"));
        originList.add(new Origin("63", "AUSTRALIA"));
        originList.add(new Origin("64", "AUSTRIA"));
        originList.add(new Origin("65", "BELGIUM"));
        originList.add(new Origin("66", "BOLIVIA"));
        originList.add(new Origin("67", "BRAZIL"));
        originList.add(new Origin("68", "BULGARIA"));
        originList.add(new Origin("69", "CANADA"));
        originList.add(new Origin("6A", "ARMENIA"));
        originList.add(new Origin("6B", "AZERBAIJAN"));
        originList.add(new Origin("6C", "BELARUS"));
        originList.add(new Origin("6D", "ESTONIA"));
        originList.add(new Origin("6E", "GEORGIA"));
        originList.add(new Origin("6F", "KAZAKHSTAN"));
        originList.add(new Origin("6G", "KYRGYZSTAN"));
        originList.add(new Origin("6H", "LATVIA"));
        originList.add(new Origin("6I", "LITHUANIA"));
        originList.add(new Origin("6J", "MOLDOVA"));
        originList.add(new Origin("6K", "RUSSIA OR THE RUSSIAN FEDERATION"));
        originList.add(new Origin("6L", "TAJIKISTAN"));
        originList.add(new Origin("6M", "TURKMENISTAN"));
        originList.add(new Origin("6N", "UKRAINE"));
        originList.add(new Origin("6O", "UZBEKISTAN"));
        originList.add(new Origin("6P", "ENGLAND"));
        originList.add(new Origin("6Q", "WALES"));
        originList.add(new Origin("6R", "THE CHANNEL ISLANDS"));
        originList.add(new Origin("6S", "THE ISLES OF WIGHT & MAN"));
        originList.add(new Origin("6T", "SCILLY ISLANDS"));
        originList.add(new Origin("6U", "HEBRIDES"));
        originList.add(new Origin("6V", "ORKNEY & SHETLAND ISLANDS"));
        originList.add(new Origin("6W", "NORTHERN IRELAND"));
        originList.add(new Origin("6X", "SLOVENIA"));
        originList.add(new Origin("6Y", "CROATIA"));
        originList.add(new Origin("6Z", "COSTA RICA"));
        originList.add(new Origin("70", "CHILE"));
        originList.add(new Origin("71", "COLOMBIA"));
        originList.add(new Origin("72", "CYPRUS"));
        originList.add(new Origin("73", "CZECHOSLOVAKIA"));
        originList.add(new Origin("74", "EGYPT"));
        originList.add(new Origin("75", "HUNGARY"));
        originList.add(new Origin("77", "JORDAN"));
        originList.add(new Origin("78", "LIBERIA"));
        originList.add(new Origin("79", "LUXEMBOURG"));
        originList.add(new Origin("7A", "ECUADOR"));
        originList.add(new Origin("7B", "INDONESIA"));
        originList.add(new Origin("7C", "REPUBLIC OF SAN MARINO"));
        originList.add(new Origin("7D", "BELIZE"));
        originList.add(new Origin("7E", "PANAMA"));
        originList.add(new Origin("7F", "MARTINIQUE"));
        originList.add(new Origin("7G", "MACEDONIA"));
        originList.add(new Origin("7H", "GHANA"));
        originList.add(new Origin("7J", "SOMOA"));
        originList.add(new Origin("7K", "TRINIDAD/TOBAGO"));
        originList.add(new Origin("7L", "CAMEROON"));
        originList.add(new Origin("7M", "SAINT MARTIN, NETH ANTILLES"));
        originList.add(new Origin("7P", "SERBIA AND MONTENEGRO"));
        originList.add(new Origin("7Q", "ANGUILLA (BWI)"));
        originList.add(new Origin("7R", "GUADELOUPE"));
        originList.add(new Origin("7T", "WEST INDIES"));
        originList.add(new Origin("7U", "SRI LANKA (FORMERLY KNOWN AS CEYLON)"));
        originList.add(new Origin("7V", "NEPAL"));
        originList.add(new Origin("7W", "SAINT LUCIA"));
        originList.add(new Origin("7X", "REUNION"));
        originList.add(new Origin("7Y", "MONGOLIA"));
        originList.add(new Origin("7Z", "MYANMAR"));
        originList.add(new Origin("80", "MALTA"));
        originList.add(new Origin("81", "MEXICO"));
        originList.add(new Origin("82", "MOROCCO"));
        originList.add(new Origin("83", "NETHERLANDS"));
        originList.add(new Origin("84", "NEW ZEALAND"));
        originList.add(new Origin("85", "PERU"));
        originList.add(new Origin("86", "ROMANIA"));
        originList.add(new Origin("87", "SWITZERLAND"));
        originList.add(new Origin("89", "TUNISIA"));
        originList.add(new Origin("8A", "TAIWAN"));
        originList.add(new Origin("8B", "ST. VINCENT AND THE GRENADINES"));
        originList.add(new Origin("8C", "LAO PDR OR LAOS"));
        originList.add(new Origin("8D", "NAMIBIA"));
        originList.add(new Origin("8E", "BOSNIA-HERZEGOVINA"));
        originList.add(new Origin("8F", "PARAQUAY"));
        originList.add(new Origin("8G", "ZAMBIA"));
        originList.add(new Origin("8H", "MAURITIUS"));
        originList.add(new Origin("8I", "SINT MAARTEN"));
        originList.add(new Origin("8J", "WEST BANK"));
        originList.add(new Origin("8K", "BENIN"));
        originList.add(new Origin("8L", "LIECHTENSTEIN"));
        originList.add(new Origin("90", "TURKEY"));
        originList.add(new Origin("91", "SOUTH AFRICA (UNION OF)"));
        originList.add(new Origin("92", "UNITED KINGDOM"));
        originList.add(new Origin("93", "URUGUAY"));
        originList.add(new Origin("94", "U.S.S.R."));
        originList.add(new Origin("95", "VENEZUELA"));
        originList.add(new Origin("96", "CHINA"));
        originList.add(new Origin("97", "FINLAND"));
        originList.add(new Origin("98", "EEC/EU (TTB USE ONLY)"));
        originList.add(new Origin("99", "POLAND"));
        originList.add(new Origin("9A", "CAYMAN ISLANDS"));
        originList.add(new Origin("9B", "CABO VERDE"));
        originList.add(new Origin("9C", "DEMOCRATIC REPUBLIC OF THE CONGO"));
        originList.add(new Origin("9D", "SENEGAL"));
        originList.add(new Origin("9E", "MADAGASCAR, REPUBLIC OF"));
        originList.add(new Origin("9F", "SURINAME, REPUBLIC OF"));
        originList.add(new Origin("9G", "GABON"));
        originList.add(new Origin("9H", "SAN MARINO"));
        originList.add(new Origin("9I", "BHUTAN/KINGDOM OF BHUTAN"));
        originList.add(new Origin("HK", "HONG KONG"));
        originList.add(new Origin("MC", "MUTIPLE COUNTRIES"));
    }
    
    public LinkedList getList(){
        return originList;
    }
}
